### ISSUE TITLE
Github官网登不上去

### ISSUE THREAD

**Issue by SunnyGiner** [DEIT2014/team2exercise#41]
我的电脑进不了Github的网页，用了两种浏览器都没用，桌面版也出了问题。不知道为什么，Github 桌面版可以正常commit和sync，但是pull request 不能正常使用。

**Comment by meflyup** [comment]
现在呢？

**Comment by SunnyGiner** [comment]
现在正常了~

**Comment by SunnyGiner** [comment]
老师，又出现官网登不上去的问题了，我的电脑里有两个用户，这个用户不可以，但是用另一个用户登录就可以，我不知道是什么方面的问题。

**Comment by meflyup** [comment]
好的。不纠结这类问题，太浪费时间。如果你一个用户能够长期登录成功，我帮你加入这个用户吧。
